// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjjHZt__Ql3lgRYwGBxT4QV8NGNF9nHA4',
    appId: '1:293861379303:web:998586f36237139267a642',
    messagingSenderId: '293861379303',
    projectId: 'appjam5',
    authDomain: 'appjam5.firebaseapp.com',
    storageBucket: 'appjam5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglQTKeRBytCOn6sGNNDpHsWDAgF0Sc3U',
    appId: '1:293861379303:android:2d7ad532f94c8c1767a642',
    messagingSenderId: '293861379303',
    projectId: 'appjam5',
    storageBucket: 'appjam5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIeVJ8b4AmUBpXyWdGmDHL7cSbVZdGZ30',
    appId: '1:293861379303:ios:8e32555b22540efa67a642',
    messagingSenderId: '293861379303',
    projectId: 'appjam5',
    storageBucket: 'appjam5.appspot.com',
    iosBundleId: 'com.example.yonderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIeVJ8b4AmUBpXyWdGmDHL7cSbVZdGZ30',
    appId: '1:293861379303:ios:d09c7ef250ec4f3e67a642',
    messagingSenderId: '293861379303',
    projectId: 'appjam5',
    storageBucket: 'appjam5.appspot.com',
    iosBundleId: 'com.example.yonderApp.RunnerTests',
  );
}
